### PR TITLE
 0.8.7

### PR DESCRIPTION
**Pull request by olemp**
Could you publish to NPM aswell, @patrick-rodgers?

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
What do I need to do to publish the project? Are the pre-publish steps documented anywhere?

**Comment by patrick-rodgers** [comment]
@olemp - any word on steps to publish? Thanks!

**Comment by olemp** [comment]
Bit busy at the moment @patrick-rodgers - let me come back to you! 💯

**Comment by patrick-rodgers** [comment]
Any updates?

**Comment by olemp** [comment]
If I remember correctly, it should be just `gulp build` to build the project and it's ready to publish! Sorry for the delay 👍

**Comment by damsleth** [comment]
This PR now also includes moving from the deprecated sp-pnp-js to pnpjs

**Comment by wobba** [comment]
@patrick-rodgers Could you take a look and possibly merge this? :)

**Pull request closed without merging**
